# Generated by Django 5.0.6 on 2024-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, default="default-slug", max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
