# Generated by Django 5.0.6 on 2024-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_student_course_capacity_course_registered_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="registered_students",
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("student", "course")},
        ),
        migrations.AddField(
            model_name="course",
            name="registered_students",
            field=models.ManyToManyField(
                through="blog.Registration", to="blog.student"
            ),
        ),
    ]
