# Generated by Django 5.0.6 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_course_registered_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="registered_students",
        ),
        migrations.AddField(
            model_name="course",
            name="registered_students",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
