# Generated by Django 5.0.6 on 2024-06-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_course_registered_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="registered_students",
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="blog.course",
            ),
        ),
    ]
