# Generated by Django 5.0.6 on 2024-06-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_remove_course_registered_students_student_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_students",
                to="blog.course",
            ),
        ),
    ]
