# Generated by Django 5.0.6 on 2024-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_course_registered_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="institue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
