# Generated by Django 5.0.6 on 2024-06-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_student_date_of_birth_student_institue_student_major_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="institue",
        ),
    ]
