# Generated by Django 5.0.6 on 2024-06-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
